import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

function CommentsSection({ recipeId, user }) {
  const [familyId, setFamilyId] = useState(null); const [membership, setMembership] = useState(null); const [comments, setComments] = useState([]); const [text, setText] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const loadComments = async () => { if (!supabase || !recipeId || !user) return; setLoading(true); setError(''); try { const { data: currentMembership, error: membershipError } = await supabase.from('family_members').select('id, family_id, display_name, role').eq('user_id', user.id).eq('is_active', true).limit(1).maybeSingle(); if (membershipError || !currentMembership) throw new Error(membershipError?.message || 'Aucune famille active trouvée.'); setMembership(currentMembership); setFamilyId(currentMembership.family_id); const { data, error: commentsError } = await supabase.from('recipe_comments').select('id, content, created_by, created_at, updated_at').eq('recipe_id', recipeId).order('created_at', { ascending: true }); if (commentsError) throw commentsError; const rows = data ?? []; const creatorIds = [...new Set(rows.map(item => item.created_by).filter(Boolean))]; let creatorMap = new Map(); if (creatorIds.length) { const { data: members, error: membersError } = await supabase.from('family_members').select('id, display_name').in('id', creatorIds); if (membersError) throw membersError; creatorMap = new Map((members ?? []).map(member => [member.id, member.display_name])) } setComments(rows.map(item => ({ ...item, creatorName: creatorMap.get(item.created_by) || 'Membre de la famille' }))) } catch (loadError) { setError(loadError.message || 'Impossible de charger les souvenirs.') } finally { setLoading(false) } }
  useEffect(() => { loadComments() }, [recipeId, user?.id])
  const addComment = async event => { event.preventDefault(); const content = text.trim(); if (!content || !supabase || !membership || membership.role === 'viewer') return; setSaving(true); setError(''); try { const { error: insertError } = await supabase.from('recipe_comments').insert({ family_id: familyId, recipe_id: recipeId, content, created_by: membership.id }); if (insertError) throw insertError; setText(''); await loadComments() } catch (saveError) { setError(saveError.message || 'Impossible d’ajouter ce souvenir.') } finally { setSaving(false) } }
  return <section className="comments-section"><div className="comments-heading"><p className="section-kicker">Commentaires & souvenirs</p></div>{error && <div className="form-error comments-message">{error}</div>}{loading ? <div className="status-card">Chargement des souvenirs…</div> : <><div className="comments-list">{comments.length === 0 ? <div className="comments-empty">Aucun souvenir n’a encore été partagé. Soyez le premier à raconter l’histoire de cette recette.</div> : comments.map(comment => <article className="comment-card" key={comment.id}><div className="comment-card-header"><strong>{comment.creatorName}</strong><time dateTime={comment.created_at}>{new Date(comment.created_at).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })}</time></div><p>{comment.content}</p></article>)}</div>{membership?.role === 'viewer' ? <div className="comments-empty">Votre rôle est « lecture seule » : vous pouvez consulter les souvenirs, mais pas en ajouter.</div> : <form className="comment-form" onSubmit={addComment}><label>Votre souvenir<textarea value={text} onChange={e => setText(e.target.value)} rows="4" maxLength="2000" placeholder="Ex. Mamie ajoutait toujours une cuillère de…" /></label><div className="comment-form-footer"><span>{text.length}/2000</span><button type="submit" className="primary-button" disabled={saving || !text.trim()}>{saving ? 'Enregistrement…' : 'Partager le souvenir'}</button></div></form>}</>}</section>
}

export default CommentsSection
