import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

function MediaSection({ recipeId, user }) {
  const [familyId, setFamilyId] = useState(null); const [membership, setMembership] = useState(null); const [photos, setPhotos] = useState([]); const [originals, setOriginals] = useState([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const loadMedia = async () => { if (!supabase || !recipeId || !user) return; setLoading(true); setError(''); setMessage(''); try { const { data: currentMembership, error: membershipError } = await supabase.from('family_members').select('id, family_id, role').eq('user_id', user.id).eq('is_active', true).limit(1).maybeSingle(); if (membershipError || !currentMembership) throw new Error(membershipError?.message || 'Aucune famille active trouvée.'); setMembership(currentMembership); setFamilyId(currentMembership.family_id); const { data, error: mediaError } = await supabase.from('media').select('id, storage_path, media_type, mime_type, original_filename, caption, position, created_at').eq('recipe_id', recipeId).order('position', { ascending: true }).order('created_at', { ascending: true }); if (mediaError) throw mediaError; const signed = await Promise.all((data ?? []).map(async item => { const { data: signedData } = await supabase.storage.from('family-media').createSignedUrl(item.storage_path, 3600); return { ...item, signedUrl: signedData?.signedUrl || '' } })); setPhotos(signed.filter(item => item.media_type === 'photo')); setOriginals(signed.filter(item => item.media_type === 'scan')) } catch (loadError) { setError(loadError.message || 'Impossible de charger les médias.') } finally { setLoading(false) } }
  useEffect(() => { loadMedia() }, [recipeId, user?.id])
  const uploadFiles = async (event, kind) => { const files = Array.from(event.target.files || []); event.target.value = ''; if (!files.length || !familyId || !supabase || membership?.role === 'viewer') return; if (kind === 'original' && originals.length > 0) return setError('Le manuscrit original existe déjà. Il reste volontairement immuable depuis l’application.'); setUploading(true); setError(''); setMessage(''); try { for (const file of files) { const extension = file.name.includes('.') ? `.${file.name.split('.').pop().toLowerCase()}` : ''; const id = crypto.randomUUID(); const folder = kind === 'photo' ? `recipes/${recipeId}/photos` : `originals/${recipeId}`; const path = `${familyId}/${folder}/${id}${extension}`; const { error: uploadError } = await supabase.storage.from('family-media').upload(path, file, { contentType: file.type || undefined, upsert: false }); if (uploadError) throw uploadError; const { error: mediaError } = await supabase.from('media').insert({ family_id: familyId, recipe_id: recipeId, storage_path: path, media_type: kind === 'photo' ? 'photo' : 'scan', mime_type: file.type || null, original_filename: file.name, position: kind === 'photo' ? photos.length : 0, created_by: membership.id }); if (mediaError) throw mediaError } setMessage(kind === 'photo' ? 'Photo(s) ajoutée(s) à la recette.' : 'Le manuscrit original a été conservé dans le livre familial.'); await loadMedia() } catch (uploadError) { setError(uploadError.message || 'Impossible d’importer le fichier.') } finally { setUploading(false) } }
  if (loading) return <section className="media-section"><div className="status-card">Chargement des photos et du manuscrit…</div></section>
  const canUpload = membership?.role !== 'viewer'
  return <section className="media-section"><div className="media-heading"><div><p className="section-kicker">Le patrimoine visuel</p><h3>Photos & manuscrit original</h3><p>Les documents originaux restent privés et ne sont jamais remplacés par une nouvelle version.</p></div></div>{error && <div className="form-error media-message">{error}</div>}{message && <div className="media-success">{message}</div>}<div className="media-block"><div className="media-block-heading"><div><h4>📷 Photos de la recette</h4><p>Ajoutez les photos du plat, de la préparation ou des moments en famille.</p></div>{canUpload && <label className="secondary-button upload-button">{uploading ? 'Import…' : '＋ Ajouter des photos'}<input type="file" accept="image/*" multiple disabled={uploading} onChange={e => uploadFiles(e, 'photo')} /></label>}</div>{photos.length === 0 ? <div className="media-empty">Aucune photo pour le moment.</div> : <div className="photo-grid">{photos.map(photo => <figure className="photo-card" key={photo.id}>{photo.signedUrl ? <img src={photo.signedUrl} alt={photo.caption || photo.original_filename || 'Photo de la recette'} /> : <div className="photo-unavailable">Image indisponible</div>}{photo.caption && <figcaption>{photo.caption}</figcaption>}</figure>)}</div>}</div><div className="media-block original-block"><div className="media-block-heading"><div><p className="section-kicker">Pièce originale</p><h4>✍️ Manuscrit de Mamie</h4><p>Cette pièce est conservée comme document patrimonial. Une fois déposée, elle n’est pas modifiable depuis l’application.</p></div>{canUpload && originals.length === 0 && <label className="primary-button upload-button">{uploading ? 'Import…' : '＋ Ajouter le manuscrit'}<input type="file" accept="image/*,.pdf,application/pdf" disabled={uploading} onChange={e => uploadFiles(e, 'original')} /></label>}</div>{originals.length === 0 ? <div className="media-empty manuscript-empty">Aucun manuscrit original n’a encore été numérisé pour cette recette.</div> : <div className="original-list">{originals.map(original => <div className="original-card" key={original.id}>{original.signedUrl && original.mime_type?.startsWith('image/') ? <img src={original.signedUrl} alt="Manuscrit original de Mamie" className="manuscript-image" /> : <div className="document-preview"><span>📜</span><strong>{original.original_filename || 'Document original'}</strong><small>{original.mime_type || 'Document'}</small></div>}{original.signedUrl && <a className="secondary-button" href={original.signedUrl} target="_blank" rel="noreferrer">Ouvrir le document</a>}</div>)}</div>}</div></section>
}

export default MediaSection
